### PR TITLE
Use async tests

### PR DESCRIPTION
**Pull request by TrySound**

### CODE REVIEW

**Comment by TrySound** [comment]
@andyjansson If you don't have a time for maintaining you can give me access.

**Comment by andyjansson** [comment]
Looks like you've rewritten the tests just for the sake of it. What's the big win here?

**Comment by andyjansson** [comment]
Also you should remove the promise polyfill as I've removed node.js 0.10 from .travis.yml

**Comment by TrySound** [comment]
@andyjansson Done!

**Comment by borodean** [comment]
@andyjansson this allows testing for async functions https://github.com/andyjansson/postcss-functions/pull/10

**Comment by TrySound** [comment]
@andyjansson If you aren't interested or don't have a time you can give me access.

**Comment by andyjansson** [comment]
@TrySound I'm dealing with some stuff right now so please don't pressure me. I'll work on my projects if and when it suits me and my situation.

**Comment by borodean** [comment]
@andyjansson how may we help you with that?

**Pull request merged**
