### PR TITLE
Update dependencies

### PR DESCRIPTION
**Pull request by borodean**
Updates PostCSS and the rest of dependencies (https://github.com/borodean/postcss-assets/issues/70).

### CODE REVIEW

**Comment by borodean** [comment]
@andyjansson would you please publish the update?

**Comment by andyjansson** [comment]
I'll be away for the rest of the week. Starting next week, I'm planning on working on some updates for the package. After those are in place, I'll publish. Stay tuned!

**Comment by onigoetz** [comment]
Hi, @andyjansson when do you plan to release this change ? can we help with something ?

**Comment by andyjansson** [comment]
@onigoetz: I'm currently in the process of moving to another city, so it will be a few weeks.

**Pull request merged**
