### PR TITLE
Fix example with promised way

### PR DESCRIPTION
**Pull request by TrySound**
`process().css` is just for debug and it shouldn't be used in production code. Also it shouldn't be an example of usage caz it can confuse users.

### CODE REVIEW

**Comment by andyjansson** [comment]
I don't know if what you're saying is true, since it's not stated anywhere in the documentation that it's just for debug and shouldn't be used. Nevertheless, I am accepting the PR.

**Comment by ai** [comment]
PostCSS Runner Guidelines has a rule to use only asynchronous methods, because it is better for performance

**Comment by ai** [comment]
But this rule is not mandatory for all cases. If your plugin is sync it is OK to use sync shortcuts. You know, PostCSS is very liberal :-)

**Pull request merged**
